# Generated by Django 4.2.15 on 2024-10-07 07:07

from django.db import migrations
import django.utils.timezone
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_notes_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=froala_editor.fields.FroalaField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=froala_editor.fields.FroalaField(default=3),
            preserve_default=False,
        ),
    ]
