# Generated by Django 4.2.15 on 2024-10-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_note_description_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
